// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Values sourced directly from google-services.json (project: myfishapp-4e3e6)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiHatyHKL8pKdpH5quGWD3ExcomaYFEXE',
    appId: '1:909011184334:android:bbd849d01d640d70a37e9f',
    messagingSenderId: '909011184334',
    projectId: 'myfishapp-4e3e6',
    databaseURL:
        'https://myfishapp-4e3e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfishapp-4e3e6.firebasestorage.app',
  );
}
